AWSTemplateFormatVersion: 2010-09-09

Description: Stack creates roles and permissions needed for BlueChipTek's Optimized Cloud Management System (OCMS) to access your account.

Parameters:
  AwsAccountLinking:
    Description: Setting to True allows for the OCMS to link AWS to BCT
    Type: String
    Default: false

  BctMasterAccountAccountId:
    Description: AWS Account Id of the BCT Master account.
    Type: String
    Default: 555703595940

  OcmsAccountId:
    Description: AWS Account Id running the OCMS
    Type: String
    Default: 992800822204

  OcmsExternalId:
    Description: External Id used by the OCMS to access your AWS account
    Type: String


Conditions:
  # Here we want to set the condition ResaleDeploy if the param
  # AwsAccountLinking is set to something other than false.
  #
  # CFN isn't straightforward when wanting to check NOT condition, see
  # https://stackoverflow.com/questions/41106216/negate-a-condition-in-cloudformation-template
  # for more details
  AwsAccountLinkingParam: !Equals [ !Ref AwsAccountLinking, false]
  ResaleDeploy: !Not [Condition: AwsAccountLinkingParam]

Resources:
  OptimizedCloudManagerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BctOptimizedCloudManager
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref OcmsAccountId
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref OcmsExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AmazonGuardDutyReadOnlyAccess

  ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: BctOcmsReadOnly
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - autoscaling:Describe*
              - aws-portal:ViewBilling
              - aws-portal:ViewUsage
              - cloudformation:ListStacks
              - cloudformation:ListStackResources
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:GetTemplate
              - cloudfront:Get*
              - cloudfront:List*
              - cloudtrail:DescribeTrails
              - cloudtrail:ListTags
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - config:Get*
              - config:Describe*
              - config:Deliver*
              - config:List*
              - cur:Describe*
              - dms:Describe*
              - dms:List*
              - dynamodb:DescribeTable
              - dynamodb:List*
              - ec2:Describe*
              - ec2:GetReservedInstancesExchangeQuote
              - ecs:List*
              - ecs:Describe*
              - elasticache:Describe*
              - elasticache:ListTagsForResource
              - elasticbeanstalk:Check*
              - elasticbeanstalk:Describe*
              - elasticbeanstalk:List*
              - elasticbeanstalk:RequestEnvironmentInfo
              - elasticbeanstalk:RetrieveEnvironmentInfo
              - elasticfilesystem:Describe*
              - elasticloadbalancing:Describe*
              - elasticmapreduce:Describe*
              - elasticmapreduce:List*
              - es:List*
              - es:Describe*
              - firehose:ListDeliveryStreams
              - firehose:DescribeDeliveryStream
              - iam:List*
              - iam:Get*
              - iam:GenerateCredentialReport
              - kinesis:Describe*
              - kinesis:List*
              - lambda:List*
              - redshift:Describe*
              - route53:Get*
              - route53:List*
              - rds:Describe*
              - rds:ListTagsForResource
              - s3:List*
              - s3:GetBucketTagging
              - s3:GetBucketLocation
              - s3:GetBucketLogging
              - s3:GetBucketVersioning
              - s3:GetBucketWebsite
              - sagemaker:Describe*
              - sagemaker:List*
              - sdb:GetAttributes
              - sdb:List*
              - ses:Get*
              - ses:List*
              - sns:Get*
              - sns:List*
              - sqs:GetQueueAttributes
              - sqs:ListQueues
              - storagegateway:List*
              - storagegateway:Describe*
              - workspaces:Describe*
            Resource: "*"
      Roles:
        - !Ref OptimizedCloudManagerRole

  BctMasterAccountRole:
    Type: AWS::IAM::Role
    Condition: ResaleDeploy
    Properties:
      RoleName: BctMasterAccount
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref BctMasterAccountAccountId
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSSupportAccess

  AcceptAccountLinkRequestPolicy:
    Type: AWS::IAM::Policy
    Condition: ResaleDeploy
    Properties:
      PolicyName: BctAcceptAccountLinkRequest
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - organizations:ListHandshakesForAccount
              - organizations:AcceptHandshake
              - organizations:DeclineHandshake
            Resource: arn:aws:organizations::555703595940:handshake/*
      Roles:
        - !Ref BctMasterAccountRole

Outputs:
  OptimizedCloudManagerRoleArn:
    Value: !GetAtt OptimizedCloudManagerRole.Arn

  BctMasterAccountRoleArn:
    Condition: ResaleDeploy
    Value: !GetAtt BctMasterAccountRole.Arn
