AWSTemplateFormatVersion: 2010-09-09

Description: Stack creates roles and permissions needed for CloudHealth.

Parameters:
  CloudHealthExternalId:
    Description: External Id used for CloudHealth to access role
    Type: String
  DbrBucket:
    Description: Bucket used to store your Detailed Billing Records
    Type: String
    Default: NullBucket
  CurBucket:
    Description: Bucket used to store your Cost and Usage Reports
    Type: String
    Default: NullBucket
  CloudTrailBucket:
    Description: Bucket used to store your CloudTrail events
    Type: String
    Default: NullBucket
  AwsConfigBucket:
    Description: Bucket used to store your AWS Config items
    Type: String
    Default: NullBucket

Conditions:
  DbrNullBucket: !Equals [ !Ref DbrBucket, NullBucket]
  ConfigureDbrBucket: !Not [Condition: DbrNullBucket]
  
  CurNullBucket: !Equals [ !Ref CurBucket, NullBucket]
  ConfigureCurBucket: !Not [Condition: CurNullBucket]
  
  CloudTrailNullBucket: !Equals [ !Ref CloudTrailBucket, NullBucket]
  ConfigureCloudTrailBucket: !Not [Condition: CloudTrailNullBucket]
  
  AwsConfigNullBucket: !Equals [ !Ref AwsConfigBucket, NullBucket]
  ConfigureAwsConfigBucket: !Not [Condition: AwsConfigNullBucket]

Resources:
  CloudHealthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudHealth
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: 454464851268
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref CloudHealthExternalId

  ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudHealthReadOnly
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - autoscaling:Describe*
          - aws-portal:ViewBilling
          - aws-portal:ViewUsage
          - cloudformation:ListStacks
          - cloudformation:ListStackResources
          - cloudformation:DescribeStacks
          - cloudformation:DescribeStackEvents
          - cloudformation:DescribeStackResources
          - cloudformation:GetTemplate
          - cloudfront:Get*
          - cloudfront:List*
          - cloudtrail:DescribeTrails
          - cloudtrail:ListTags
          - cloudwatch:Describe*
          - cloudwatch:Get*
          - cloudwatch:List*
          - config:Get*
          - config:Describe*
          - config:Deliver*
          - config:List*
          - cur:Describe*
          - dynamodb:DescribeTable
          - dynamodb:List*
          - ec2:Describe*
          - elasticache:Describe*
          - elasticache:ListTagsForResource
          - elasticbeanstalk:Check*
          - elasticbeanstalk:Describe*
          - elasticbeanstalk:List*
          - elasticbeanstalk:RequestEnvironmentInfo
          - elasticbeanstalk:RetrieveEnvironmentInfo
          - elasticfilesystem:Describe*
          - elasticloadbalancing:Describe*
          - elasticmapreduce:Describe*
          - elasticmapreduce:List*
          - es:List*
          - es:Describe*
          - iam:List*
          - iam:Get*
          - iam:GenerateCredentialReport
          - kinesis:Describe*
          - kinesis:List*
          - lambda:List*
          - redshift:Describe*
          - route53:Get*
          - route53:List*
          - rds:Describe*
          - rds:ListTagsForResource
          - s3:List*
          - s3:GetBucketTagging
          - s3:GetBucketLocation
          - s3:GetBucketLogging
          - s3:GetBucketVersioning
          - s3:GetBucketWebsite
          - sdb:GetAttributes
          - sdb:List*
          - ses:Get*
          - ses:List*
          - sns:Get*
          - sns:List*
          - sqs:GetQueueAttributes
          - sqs:ListQueues
          - storagegateway:List*
          - storagegateway:Describe*
          - workspaces:Describe*
          Resource: "*"
      Roles:
        - !Ref CloudHealthRole

  ReadDbrBucket:
    Type: AWS::IAM::Policy
    Condition: ConfigureDbrBucket
    Properties:
      PolicyName: CloudHealthReadDbrBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - Fn::Sub: "arn:aws:s3:::${DbrBucket}"
              - Fn::Sub: "arn:aws:s3:::${DbrBucket}/*"
      Roles:
        - !Ref CloudHealthRole

  ReadCurBucket:
    Type: AWS::IAM::Policy
    Condition: ConfigureCurBucket
    Properties:
      PolicyName: CloudHealthReadCurBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - Fn::Sub: "arn:aws:s3:::${CurBucket}"
              - Fn::Sub: "arn:aws:s3:::${CurBucket}/*"
      Roles:
        - !Ref CloudHealthRole
  ReadCloudTrailBucket:
    Type: AWS::IAM::Policy
    Condition: ConfigureCloudTrailBucket
    Properties:
      PolicyName: CloudHealthReadCloudTrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - Fn::Sub: "arn:aws:s3:::${CloudTrailBucket}"
              - Fn::Sub: "arn:aws:s3:::${CloudTrailBucket}/*"
      Roles:
        - !Ref CloudHealthRole

  ReadAwsConfigBucket:
    Type: AWS::IAM::Policy
    Condition: ConfigureAwsConfigBucket
    Properties:
      PolicyName: CloudHealthReadAwsConfigBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - Fn::Sub: "arn:aws:s3:::${AwsConfigBucket}"
              - Fn::Sub: "arn:aws:s3:::${AwsConfigBucket}/*"
      Roles:
        - !Ref CloudHealthRole

Outputs:
  CloudHealthRoleArn:
    Value: !GetAtt CloudHealthRole.Arn
    Export:
      Name: BctCloudHealthRoleArn

